import pandas as p
import sqlite3
import matplotlib.pyplot as plot
f= p.read_csv("train.csv")
#print(f.head())
#print(f.columns)
#print(f.isnull().sum())
#print(f.dtypes)
f['Order Date'] = p.to_datetime(f['Order Date'], dayfirst=True)
#print(f.dtypes)
f['Month']= f['Order Date'].dt.to_period('M')
#print(f.dtypes)
sales_for_month= f.groupby('Month')['Sales'].sum()
print(sales_for_month)
top5_salaing_products= f.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(5)
print(top5_salaing_products)
f['Month']=f['Month'].astype(str)
conect= sqlite3.connect("sales.db")
f.to_sql("Sales", conect, if_exists='replace', index=False)
conect.close()
print("data saved in db successfully")
sales_for_month.plot(kind='line', title='monthly sales')
plot.show()
top5_salaing_products.plot(kind='bar', title='Top 5 proudcts')
plot.show()
